language: ruby
rvm:
  - 2.5
  - 2.6

# from { personal } gem theme
# install: gem install jekyll jemoji html-proofer
# script: jekyll serve --baseurl "" --detach && htmlproofer ./_site --disable-external --empty-alt-ignore

before_install:
  - gem install bundler
git:
  depth: 1

script:
  - bundle exec jekyll build
  # - bundle exec html-proofer ./_site --only-4xx --check-html --allow_hash_ref --assume-extension --alt-ignore '/.*/'
branches:
  only:
    - master
after_success:
  - bundle exec rake deploy:branch
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # JEKYLL_ENV=production