language: ruby
rvm:
  - 2.5
  - 2.6

# from { personal } gem theme
# install: gem install jekyll jemoji html-proofer
# script: jekyll serve --baseurl "" --detach && htmlproofer ./_site --disable-external --empty-alt-ignore

before_install:
  - gem install bundler
git:
  depth: 1
branches:
  only:
    - master
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # JEKYLL_ENV=production

script:
  - bundle exec jekyll build
    # - bundle exec html-proofer ./_site --only-4xx --check-html --allow_hash_ref --assume-extension --alt-ignore '/.*/'
after_success:
  - bundle exec rake deploy:branch

deploy:
  provider: s3
  access_key_id: S3_ACCESS_KEY_ID
  secret_access_key: S3_SECRET
  skip_cleanup: true
  bucket: "sc-lib-ds-static"
  upload-dir: jerky-vast-ills
  detect-encoding: true
  default_text_charset: 'utf-8'